### ISSUE TITLE
Conflict with LinkPlugin

### ISSUE THREAD

**Issue by marksweb** [fsbraun/djangocms-frontend#12]
**Describe the bug**
With the issues I'm having with select2 for djangocms-url-manager, I can't currently add plugins that have a link. The `url_grouper` field from the url-manager form is required, but I can't complete it because I don't have any URL in url-manager.

So I've added djangocms-link to the project and now I'm seeing naming conflict on `LinkPlugin` during server startup;

```
cms.exceptions.PluginAlreadyRegistered: Cannot register <class 'djangocms_link.cms_plugins.LinkPlugin'>, a plugin with this name ('LinkPlugin') is already registered.
```

**To Reproduce**
1. Running cms v4 with djangocms_frontend and djangocms_link installed.
2. Start a server
3. Observe the above plugin registration error

**Comment by marksweb** [comment]
Oh man. I'm so tired I didn't even realise how silly that was while I was typing it 😂

**Comment by fsbraun** [comment]
I suggest to either add URL in the url manager or remove it from `INSTALLED_APPS`. Then you'll find the traditional link functionality (without the need for `djangocms_link`.
