### ISSUE TITLE
Attributes not being added to a heading

### ISSUE THREAD

**Issue by marksweb** [fsbraun/djangocms-frontend#13]
The template uses `instance.attributes_str` but I'm not seeing my classes on a heading.

**To Reproduce**
1. Create a heading plugin
2. Click on advanced settings and add classes
3. Save the plugin
4. No classes seen on heading

**Expected behavior**
I'm expecting the heading to render with my classes.

**Screenshots**
![Screenshot 2022-03-19 at 23 20 09](https://user-images.githubusercontent.com/1461191/159141667-0d7c3b6e-735d-482c-bc66-f5df025e7bab.png)

**Additional context**
The two headings seen in the above image are copies of one-another. The first was created as a child of another element. Then I created a copy to verify it wasn't somehow related to it being a child.

**Comment by fsbraun** [comment]
Fixed by https://github.com/fsbraun/djangocms-frontend/commit/bf15bd33dcadc8eb1891e261b08a2db7cbd15fa6 ! Thanks!
