### ISSUE TITLE
Both min and max size field for text area field have text "Minimum text length:"

### ISSUE THREAD

**Issue by rolandf** [fsbraun/djangocms-frontend#15]
<label for="[id_min_length]()">Minimum text length:</label>
                        
                            <input type="[number]()" name="[min_length]()" value="[0]()" id="[id_min_length]()">
                        
                    
                    
                </div>
            
                <div class="[fieldBox field-max_length]()">
                    
                    
                        <label class="[inline]()" for="[id_max_length]()">**Minimum text length**:</label>

**Comment by fsbraun** [comment]
So true... Thanks!

**Comment by fsbraun** [comment]
Fixed with in commit https://github.com/fsbraun/djangocms-frontend/commit/01fdab3c66bd5f1c4a6e28fd82cdb151384d7120  :-)
