### ISSUE TITLE
How Fully will DjangoCMS Proper Support this Plugin?

### ISSUE THREAD

**Issue by tacc-wbomar** [fsbraun/djangocms-frontend#8]
**Is your feature request related to a problem? Please describe.**
I am wary of this software because:
- My project is in production.
- This project is not at 1.0 yet.
- I've seen large Django CMS apps begin to die.

**Describe the solution you'd like**
Answers:

1. Is this project intended to be "endorsed by the [django CMS Association](https://www.django-cms.org/en/about-us/)"?
2. Will https://github.com/django-cms/djangocms-bootstrap4 be deprecated?
3. Will this plugin bundle die if https://github.com/gl-agnx/djangocms-bootstrap5 dies?

**Describe alternatives you've considered**
None.

**Additional context**
I am interesting in this software, because of problems with https://github.com/django-cms/djangocms-bootstrap4 and the hope to leave or improve or reliance on Bootstrap.

**Comment by marksweb** [comment]
@tacc-wbomar This is probably worthy of 1.0 as it stands. It's certainly not unstable. I've been building it into a project for a week or so using a bootstrap theme.

1. Yes, the plan is to move this under the dCA officially.
2. That's likely the outcome.
3. No, the package essentially has nothing to do with that anymore. That related repo was started when we wanted to introduce bootstrap5 support but it didn't really go anywhere. With this package @fsbraun has done a lot of work to create what is effectively a brand new package with much better architecture.

**Comment by fsbraun** [comment]
Hi @tacc-wbomar ! Thanks for looking at djangocms-frontend. I second @marksweb 's assessment though I cannot comment on 2. I myself use djangocms-frontend in production and plan to keep it that way.

I'm seeing that it also runs under the current development version of Django CMS 4 to ensure compatibility for the future.

I really plan to move to a 1.0 version soon. To not leave your weariness with words only, maybe it also is an opportunity for you to check djangocms-frontend and its migration feature on a test system and make your needs known before we freeze 1.0. Contributions are welcome, of course!

**Comment by tacc-wbomar** [comment]
Sounds great, thank you both. I am more inclined to out this project.
